enum constants {
    ADD_A_ITEM = 'ADD_A_ITEM',
    REMOVE_A_ITEM = 'REMOVE_A_ITEM',
    REMOVE_ALL_COMPLETED_ITEMS = 'REMOVE_ALL_COMPLETED_ITEMS',
    TOGGLE_COMPLETED_ITEM = 'TOGGLE_COMPLETED_ITEM',
    EDIT_ITEM = 'EDIT_ITEM'
}

export default constants